<?php

namespace Database\Seeders;

use App\Models\DoctorServiceRelation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DoctorService;

class DoctorServiceRelationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // أسنان

        // layla
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>1,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>2,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>3,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>4,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>5,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>6,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>7,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>8,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>9,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>10,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>1,
            'doctor_service_id'=>11,
        ]);
        // sondos
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>1,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>2,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>3,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>4,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>5,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>6,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>9,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>10,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>11,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>12,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>13,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>14,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>15,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>16,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>17,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>2,
            'doctor_service_id'=>18,
        ]);

        // safaa
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>11,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>23,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>24,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>25,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>26,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>27,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>28,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>29,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>30,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>3,
            'doctor_service_id'=>31,
        ]);
        // badrya
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>1,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>2,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>3,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>4,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>5,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>6,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>7,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>8,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>9,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>10,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>11,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>19,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>20,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>21,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>4,
            'doctor_service_id'=>22,
        ]);
        // Ahmad
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>1,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>2,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>3,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>4,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>5,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>6,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>7,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>8,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>9,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>10,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>11,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>19,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>20,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>21,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>5,
            'doctor_service_id'=>22,
        ]);


        //جراحات التجميل

        // – د. فقيه
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>31,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>32,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>33,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>34,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>35,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>36,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>37,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>38,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>39,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>40,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>41,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>42,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>43,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>6,
            'doctor_service_id'=>44,
        ]);

        // الجلدية

        // – – د: حسام الدين
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>45,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>46,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>47,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>48,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>49,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>50,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>51,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>52,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>7,
            'doctor_service_id'=>53,
        ]);

        // الدايت واللايف ستايل

        // – أ.مي القاسم
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>54,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>55,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>56,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>57,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>58,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>59,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>60,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>61,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>62,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>63,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>64,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>65,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>66,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>67,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>68,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>69,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>70,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>71,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>72,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>73,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>74,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>75,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>76,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>77,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>78,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>9,
            'doctor_service_id'=>79,
        ]);

        // البشرة

        // أ – شيرين السباعي
        DoctorServiceRelation::create([
            'doctor_id'=>8,
            'doctor_service_id'=>80,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>8,
            'doctor_service_id'=>81,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>8,
            'doctor_service_id'=>82,
        ]);
        DoctorServiceRelation::create([
            'doctor_id'=>8,
            'doctor_service_id'=>83,
        ]);
    }
}
